name: default

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to container registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u USERNAME --password-stdin
      - name: Pull container images
        run: docker-compose pull || true
      - name: Build and start containers
        run: docker-compose up -d --build
      - name: Push container images
        run: |
          docker-compose push php && \
          docker-compose push nginx && \
          docker-compose push nodejs && \
          docker-compose push chrome
      - name: Install stylelint
        run: |
          docker-compose exec -T nodejs yarn add stylelint stylelint-config-standard && \
          docker-compose exec -T nodejs sh -c "echo '{\"extends\": \"stylelint-config-standard\"}' > .stylelintrc.json"
      - name: Lint CSS
        run: docker-compose exec -T nodejs yarn stylelint vendor/nedac/sylius-temporarily-out-of-stock-plugin/src/Resources/public/
      - name: Install sub dependencies
        run: docker-compose exec -T php sh -c "(cd vendor/nedac/sylius-temporarily-out-of-stock-plugin && composer install)"
      - name: Install phpcpd
        run: docker-compose exec -T php phive install --trust-gpg-keys 4AA394086372C20A phpcpd
      - name: Cod